Add `files` option
kevva/dir-glob pull request #3
Opened 2017-07-03 18:07 UTC by kevva

Probably room for some improvement here and there, but it's functioning at least :)

@sindresorhus @SamVerschueren @schnittstabil

2017-07-07 22:38 UTC, sindresorhus requested changes

2017-07-07 22:38 UTC, sindresorhus commented on index.js
> +const isDirectoryP = pify(isDirectory);
Instead of using `pify` here, just use https://github.com/sindresorhus/path-type instead

2017-07-07 22:38 UTC, sindresorhus commented on index.js
> +		.then(globs => globs.reduce((a, b) => a.concat(b), []));
`[].concat.apply([], globs);` instead?

2017-07-07 22:39 UTC, sindresorhus commented
How does the `files` option handle filenames with a dot? Like `webpack.config` where the full name is `webpack.config.js`.

2017-07-08 12:22 UTC, kevva commented on index.js
> +const isDirectoryP = pify(isDirectory);
Used `is-directory` because it doesn't `throw` when the path doesn't exist. Could handle it here, but I thought it was cleaner not to.

2017-07-08 13:35 UTC, sindresorhus commented on index.js
> +const isDirectoryP = pify(isDirectory);
`path-type` doesn't throw either, it just returns a boolean.

2017-07-08 15:15 UTC, kevva commented on index.js
> +const isDirectoryP = pify(isDirectory);
Yes, it does. You aren't handling `ENOENT` anywhere. Tests are failing when using it:

```
convert directories to glob - async

  Rejected promise returned by test. Reason:

  Error {
    code: 'ENOENT',
    errno: -2,
    path: 'foo/**',
    syscall: 'stat',
    message: 'ENOENT: no such file or directory, stat \'foo/**\'',
  }
```

2017-07-08 17:16 UTC, sindresorhus commented on index.js
> +const isDirectoryP = pify(isDirectory);
Oh. That is definitely not the intention. PR would be lovely :)

2017-07-08 23:21 UTC, sindresorhus approved these changes

2017-07-09 16:14 UTC, kevva commented
> How does the `files` option handle filenames with a dot? Like `webpack.config` where the full name is `webpack.config.js`.

It doesn't atm. Any ideas?

2017-07-09 16:28 UTC, sindresorhus commented
We have to decide whether the extension is after the first or last dot.

2017-07-09 16:46 UTC, kevva commented
The last dot might be a better default since it'll cover most cases except `.tar.gz` etc. Maybe it should be configurable?

2017-07-17 19:49 UTC, sindresorhus commented
I would go with the last dot too. I don't think it should be configurable.

2017-07-21 23:13 UTC, kevva commented
Alright. What's your thoughts on https://github.com/sindresorhus/globby/pull/46#issuecomment-312863683v to increase performance?

> I'm wondering if we maybe should check if it's a glob using a regex before checking if it's a directory in the `dir-glob` module?

2017-07-22 21:25 UTC, sindresorhus commented
I don't think it's worth it. You don't usually have a lot of glob patterns, and few fs.stat checks are pretty cheap relatively to everything else involved in globbing. Using a regex will have ambiguous cases. The only way to be totally sure is to actually check the disk.

2017-07-24 00:05 UTC, kevva commented
Alright, then I think this is good to 🚢 ?

2017-07-24 11:12 UTC, merged

2017-07-24 11:12 UTC, sindresorhus commented
👍